### ISSUE TITLE
Relevancy query for an undetected goodix fingerprint sensor

### ISSUE THREAD

**Issue by Sadi58** [knauth/goodix-521d-explanation#3]
Your effort seemed promising as I haven't managed to make any progress in finding a way to use the fingerprint sensor in Linux (which works fine with the pre-installed Windows 10).
To start with, I couldn't see it detected no matter which command I use: `lsusb`, `lspci`, `xinput -list`, and finally `sudo lshw`.
Windows displays the following information about it:
```
Goodix Fingerprint SPI Device
Device ACPI\GXFP3200\4&2ec0f82c&0 was configured.
Driver Name: oem9.inf
Class Guid: {53d29ef7-377c-4d14-864b-eb3a85769359}
Driver Date: 02/13/2017
Driver Version: 1.0.20.22
Driver Provider: Goodix FP
Driver Section: MyDevice_Install.NT
Driver Rank: 0xFF0001
Matching Device Id: ACPI\GXFP3200
Outranked Drivers: oem9.inf:ACPI\GXFP3200:00FF2000
Device Updated: false
Parent Device: PCI\VEN_8086&DEV_9D29&SUBSYS_18E01043&REV_21\3&11583659&1&F2
```
I might be regarded just a bit above average user, and it seemed to me that the workaround won't work for me either, is that so?

In that case, do you have any idea why my "Goodix Fingerprint SPI Device" is not detected at all under Linux, what model it is, and if there's any hope of using it under Linux as well in not so distant future?

Thank you very much...

**Comment by knauth** [comment]
I suggest you join the ROG linux discord to get some more help. There others can offer info as well.
There's an invite link in the readme.

**Comment by Sadi58** [comment]
OK, thanks. Now I'm beginning to make some progress after getting acquainted with that Discord forum.
